apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-rest-service
spec:
  selector:
    app: spring-petclinic-rest
  ports:
    - protocol: "TCP"
      port: 9966       # Puerto interno del servicio
      targetPort: 9966 # Puerto en el contenedor
      nodePort: 30000  # Puerto específico en el NodePort
  type: NodePort